POST http://localhost:3000/register/
Content-Type: application/json

{   
    "name":"babu",
    "username":"jani",
    "password": "123456",
    "gender": "male",
    "location":"Detroit"
}
###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"jani",
    "password": "123456"
}
###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
    "username":"jani",
    "oldPassword": "123456",
    "newPassword":"654321"
}